# the secrets for the broker
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bifrost.daml.broker.secret.name" . }}
  namespace: dev
type: Opaque
data:
  daml-party: 
    "<daml party in base 64>"
  daml-token: 
    "<daml connect token, the token for the login api if daml hub, otherwise, the token for the daml node>"
  topl-keyfile: 
    "<the keyfile for the daml node>"
  topl-keyfile-password: "<the password for the keyfile>"